app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from foias import views


from django.conf import settings

if settings.USE_ALLAUTH:
    from django.contrib.auth.decorators import login_required
    from django.contrib.auth.views import logout

    admin.site.login = login_required(admin.site.login)

admin.site.site_title = 'FOIAs'
admin.site.site_header = 'FOIAs'
admin.site.index_title = 'Track your FOIAs'


urlpatterns = [
    url(r'^foias/', include('foias.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
  ]

if settings.USE_ALLAUTH:
    urlpatterns += [
        url(r'^foias/accounts/logout/$', logout, {'next_page': '/foias/admin/'}),
        url(r'^foias/accounts/', include('allauth.urls')),  
    ]

foias/urls.py
from django.conf.urls import url

from . import views
app_name = 'foias'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^healthcheck$', views.healthcheck, name="healthcheck"),
    url(r'^search$', views.search, name="search"),
    url(r'^project/([0-9]+)$', views.project, name="project"),
    url(r'^all$', views.all, name="all"),    
    url(r'^addten$', views.addten, name="addten"),


    # # this is not implemented!
	# but if you wanted a page for showing details of a FOIA other than the edit page, you'd have to uncomment this
	# and make some changes in /foias/views.py
    # ex: /foias/5/
    # url(r'^(?P<foia_id>[0-9]+)/$', views.detail, name='detail'),    
]

foias/models.py
from django.db import models
from django.core.mail import EmailMultiAlternatives
from business_calendar import Calendar
from django.contrib.auth.models import User
from django.urls import reverse
import datetime
from django.utils.safestring import mark_safe
from django.contrib.sites.models import Site
import requests
from django.conf import settings
import json

class Tag(models.Model):
  class Meta:
    verbose_name = 'Project/Tag'
    verbose_name_plural = 'Projects/Tags'  
  name = models.CharField("Tag Name", max_length=200)
  notes = models.TextField("Notes about this tag", blank=True, null=True)
  def __str__(self):
      return "{}".format(self.name)

class MyUser(User):
   class Meta:
      proxy = True
      ordering = ('first_name', 'last_name')
  
   def __str__(self):
      return self.first_name + " " + self.last_name if self.first_name and self.last_name else self.username


class SpecialPerson(models.Model):
  """a class for representing certain properties of people who aren't like other people

     like lawyers or clerks, who get notified of various steps in the FOIA process.
  """
  class Meta:
    verbose_name = 'People (Special Roles, Default Projects, etc.)'
    verbose_name_plural = 'People (Special Roles, Default Projects, etc.)'
  user = models.OneToOneField(MyUser, null=False) # many-to-one  
  is_clerk = models.BooleanField('Is this person a clerk, I mean, news assistant?', default=False)
  is_lawyer = models.BooleanField('Got a jay dee?', default=False)
  default_project = models.ForeignKey(Tag, null=True, blank=True)
  slack_handle = models.CharField("Slack Name", max_length=200, default=None, null=True)
  def __str__(self):
    if self.is_clerk and self.is_lawyer:
      return "{} is a clerk and a lawyer, which is unanticipated and probably a mistake!".format(self.user)
    elif self.is_clerk:
      return "{} is a clerk".format(self.user)
    elif self.is_lawyer:
      return "{} is a lawyer".format(self.user)
    else:
      return "{} is neither a clerk nor a lawyer.".format(self.user)

  def slack_channel(self):
    if not self.slack_handle:
      return None
    elif self.slack_handle[0] == "@":
      return self.slack_handle
    else:
      return "@{}".format(self.slack_handle)

class Agency(models.Model):
  """Represents an agency!

     Eventually, duedate stuff could be specific to agencies, e.g. noting if they don't send ack letters
     or if it's a state agency with different deadlines.
  """
  class Meta:
    verbose_name = 'Agency'
    verbose_name_plural = 'Agencies'  
    ordering = ('name',)

  name = models.CharField("Agency Name", max_length=200)
  notes = models.TextField("Notes about the agency", blank=True, null=True)
  def __str__(self):
    return self.name

class Foia(models.Model):
  class Meta:
    verbose_name = 'FOIA'
    verbose_name_plural = 'FOIAs'
    # ordering = 

  CALENDAR = 0
  BUSINESS = 1
  reporter = models.ForeignKey(MyUser, null=True,verbose_name="Who filed this request?") # many-to-one
  agency = models.ForeignKey(Agency, null=False)  

  filed_date = models.DateField('date filed')
  request_subject = models.CharField('what was the request for?', blank=True, null=True, max_length=1000)
  request_notes = models.TextField('Request text and/or notes', help_text="Did you send by mail or email? Why did you phrase it the way you did?", blank=True)
  is_state_foia = models.BooleanField("Is this a FOIA filed with a state or a foreign country?", help_text="This app doesn't know about the FOIA deadlines in those places, so you won't get notifications for these, but you're welcome to track it here.", default=False)

  received_ack_letter = models.BooleanField('Have you received an acknowledgement yet?', default=False)
  ack_date = models.DateField('date acknowledgement letter received', blank=True, null=True)
  request_number = models.CharField(max_length=200, blank=True)
  submission_notes = models.TextField('notes about the process' , blank=True, help_text="Record your phone call updates here. Did they respond by mail or email? Do you have a phone number? Did they tell you what track it\'s on?")
  date_response_due_custom = models.DateField("When are the records due? (Custom due date)", blank=True, null=True)

  received_response = models.BooleanField('Have you received responsive docs (or a denial) yet?')
  resp_date = models.DateField('date response received', blank=True, null=True)
  response_satisfactory = models.BooleanField("We're satisfied with what we got and do not need to appeal, sue or pursue this any further.", default=False)
  response_notes = models.TextField("Notes about your response.", help_text="Complain about the redactions here!", blank=True)
  response_url = models.TextField("Link to the documents and/or response letter. (Optional. Skip this if you're storing the documents on paper or offline)", blank=True, help_text="Google Drive and Dropbox are both good places to store documents and both generate shareable links you could paste here.")
  
  appealed = models.BooleanField('Have you (or your lawyer) appealed this?', default=False)
  appeal_date = models.DateField('date appeal filed', blank=True, null=True)
  lawsuit_filed = models.BooleanField('Have you (or your lawyer) filed a lawsuit over this?', default=False)
  lawsuit_filed_date = models.DateField('date lawsuit filed', blank=True, null=True)
  lawsuit_notes = models.TextField("Notes about the lawsuit ", blank=True)
  tags = models.ManyToManyField(Tag, verbose_name="What project(s) is this request a part of?", blank=True)


  # I don't want to notify people multiple times a day, ever.
  # so... this keeps track of the day of the most recent notification
  # and only sends if today is after the most recent notification date.
  last_notified = models.DateField('most recent date notified', null=True)

  # a real-life, honest-to-goodness lawyer says:
  #    The response is due 20 business days after receipt of the request (but 
  #      the agency can get a 10 business day extension if there exist "unusual circumstances").
  #    The appeal response deadline is also 20 business days after the appeal is received.
  #    The acknowledgment bit is agency by agency (it's done by regulation, generally). A lot 
  #      of them have the 10-day requirement, but I'm not sure it's true that they all do.

  ack_due_duration =             [10, BUSINESS] # 10 business days after sent (for some agencies)
  response_due_duration =        [20, BUSINESS] # 20 business days after sent (but there are extensions)
  appeal_almost_due_duration =   [85, CALENDAR] # an arbitrary Jeremy-chosen amount less than 90 days after response
  appeal_due_duration =          [90, CALENDAR] # 90 days (not business, calendar) after response
  appeal_response_due_duration = [20, BUSINESS] # 20 business days after appeal filed
  constructive_denial_duration = [90, CALENDAR] # 90 business days after acknowledgment is a constructive denail, says Derek Kravitz.

  def __str__(self):
      return "{} FOIA filed on {} by {}".format(self.agency, self.filed_date, self.reporter)

  def edit_link(self):
    return Site.objects.get_current().domain + reverse('admin:foias_foia_change', args=[self.id])


  STATUSES = {
    "LITIGATION": {
      "name": "in litigation",
      "sort_order": 10  # FOIAs in litigation are very boring (everyone who needs to know already knows)
    },
    "APPEALED": {
      "name": "appealed",
      "sort_order": 5
    },
    "RESPONSE_RECEIVED_OK": {
      "name": "response received!",
      "sort_order": 11
    },
    "RESPONSE_RECEIVED_UNAPPEALABLE": {
      "name": "response received (too late to appeal)",
      "sort_order": 6
    },
    "RESPONSE_RECEIVED_NOT_YET_APPEALED": {
      "name": "response received (not yet appealed)",
      "sort_order": 4
    },
    "ACKED": {
      "name": "acknowledged",
      "sort_order": 1
    },
    "CONSTRUCTIVELY_DENIED": {
      "name": "constructively denied?",
      "sort_order": 2
    },
    "FILED": {
      "name": "filed",
      "sort_order": 3
    },
  }

  def sort_order(self):
    """sort order for cases, based on status"""
    # apparently this is the pythonic way to do it!
    # ...
    # c'mon python.
    # these'll be sorted asc by default, so bigger numbers are at the bottom.

    return self.STATUSES[self._status()]["sort_order"]
  


  def sortable_filed_date(self):
    return self.filed_date.strftime('%s')


  def _status(self):
    if self.lawsuit_filed:
      return "LITIGATION"
    elif self.appealed:
      return "APPEALED"
    elif self.received_response: # acknowledged, responded to, but not appealed
      if self.response_satisfactory:
        return "RESPONSE_RECEIVED_OK"
      elif self.resp_date and self.date_appeal_due() < datetime.date.today():
        return "RESPONSE_RECEIVED_UNAPPEALABLE"
      else:
        return "RESPONSE_RECEIVED_NOT_YET_APPEALED"
    elif self.received_ack_letter:
      if self.constructively_denied():
        return "CONSTRUCTIVELY_DENIED"
      else:
        return "ACKED"
    else: # no lawsuit, no appeal, no response, no ack.
      return "FILED"

  def status(self):
    return self.STATUSES[self._status()]["name"]

  def is_incalculable(self):
    """For various reasons, we may not be able to know anything about certain FOIAs -- e.g. if they're filed with a state, not the feds."""
    return self.is_state_foia


  def next_due_date(self):
    if self.lawsuit_filed:
        return "ask Legal Dept."
    if self.response_satisfactory:
        return ""
    elif self.is_incalculable():
      if not self.received_response and self.date_response_due_custom:
        if self.date_response_due() < datetime.date.today():
          return "Response overdue, was due {}".format(self.date_response_due())
        else: 
          return "Agency owes us a response due {}".format(self.date_response_due())
      else:
        return "Unknown"
    else:
      if self.appealed:

foias/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from .models import Foia, Agency, Tag, SpecialPerson

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings

from datetime import datetime

@receiver(pre_save, sender=User)
def prepare_user(sender, instance, **kwargs):
    if instance._state.adding is True:

        ## Don't add users not from the nytimes.com email domain.
        ## or a few whitelisted emails for testing.

        if settings.USE_ALLAUTH:
            if instance.email and settings.ALLOWABLE_LOGIN_DOMAIN and not instance.email.split('@')[1] == settings.ALLOWABLE_LOGIN_DOMAIN:
                raise Http404('Please login with your {} email address.'.format(ALLOWABLE_LOGIN_DOMAIN))

        instance.is_staff = True
        instance.is_superuser = True

# you may want to have the front-page of the site (listing all the foias)
# require you to log in to see it.
# if so, just uncomment this.
# @login_required()
def index(request):
    latest_foias = sorted(Foia.objects.order_by('-filed_date')[:50], key=lambda f: f.sort_order())
    if request.user.is_anonymous:     
        my_foias = []
    else:
        my_foias     = sorted(Foia.objects.filter(reporter=request.user), key=lambda f: f.sort_order())
    my_foias_set = set(my_foias)

    project_foias = []
    try:
        if not request.user.is_anonymous and request.user.specialperson.default_project:
            project_foias = sorted(Foia.objects.filter(tags=request.user.specialperson.default_project), key=lambda f: f.sort_order())
            project_name = request.user.specialperson.default_project.name
    except SpecialPerson.DoesNotExist:
        pass

    # for the dashboard thingy
    my_foias_count   = len(my_foias_set) if not request.user.is_anonymous else 0
    all_foias_count  = Foia.objects.count()
    percent_overdue  = "TK" #Foia.objects.filter(reporter=request.user).count() / ??
    percent_complete =  int(float(Foia.objects.filter(received_response=True).filter(response_satisfactory=True).count())/all_foias_count*100) if not all_foias_count == 0 else "n/a"

    latest_foias = [item for item in latest_foias if item not in my_foias_set]
    return render(request, 'foias/index.html', 
        {'latest_foias': latest_foias, 
         'my_foias': my_foias, 
         'project_foias': project_foias,
         'warn_about_holidays': date.today()>date(2020, 11, 1),
         'my_foias_count': my_foias_count,
         'all_foias_count': all_foias_count,
         'percent_overdue': percent_overdue,
         'percent_complete': percent_complete,
        })

def project(request, tag_id):
    project_name = Tag.objects.get(id=tag_id).name
    project_foias = sorted(Foia.objects.filter(tags__id=tag_id), key=lambda f: f.sort_order())
    return render(request, 'foias/project.html', 
        {
         'project_foias': project_foias,
         'project_name': project_name,
         'warn_about_holidays': date.today()>date(2020, 11, 1),
        })


def addten(request):
    days_to_add = 10
    date_str = request.GET["date"]
    date = datetime.strptime(date_str, "%Y-%m-%d")
    f = Foia()
    new_date = f.cal.addbusdays(date, days_to_add).date()
    return JsonResponse({'old_date':date, 'new_date': new_date, 'days_added': days_to_add})

def healthcheck(request):
    return HttpResponse('', content_type="text/plain", status=200)

def all(request):
    """this page lists ALL the requests and is probably best for the lawyers or whoever"""
    result_foias = Foia.objects.all()
    paginator = Paginator(result_foias, 25)

    page = request.GET.get('page')
    try:
        result_foias = paginator.page(page)
    except PageNotAnInteger:
        result_foias = paginator.page(1)
    except EmptyPage:
        result_foias = paginator.page(paginator.num_pages)

    return render(request, 'foias/all.html', {'result_foias': result_foias})


# full text search method.
def search(request):
    query_string = request.GET['q']
    query = SearchQuery(query_string, config='simple')
    vector = SearchVector('reporter__first_name', 'reporter__last_name', 'agency__name', 
        'request_subject', 'request_notes', 'request_number',  'submission_notes', 
        'response_notes', 'response_url', 'lawsuit_notes', config='simple' )
    res = Foia.objects.annotate(rank=SearchRank(vector, query), search=vector).filter(search=query_string).order_by('-rank')[:50]
    return render(request, 'foias/search.html', {'result_foias': res, 'query': query_string })

# # this is not implemented!
# but if you wanted a page for showing details of a FOIA other than the edit page, this would be where to do it.
# you'd also have to change foias/urls.py
# def detail(request, foia_id):
#     foia = get_object_or_404(Foia, pk=foia_id)
#     return render(request, 'foias/detail.html', {'foia': foia})

foias/templates/foias/all.html
{% extends "base.html" %}

{% block content %}
  <div class="container">

  {% if result_foias %}
  <div class="row" style="border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of results: </p>
  </div>

    {% include "foias/foiatable.html" with foias=result_foias only %}
  {% else %}
      <p>Sorry, there are no more results.</b></p>
  {% endif %}


  {% endblock %}
</div>
{% block extrajs %}
  <script type="text/javascript">
    $(document).ready(function() 
      { 
        $("#foiastatus").tablesorter({"sortList": [[6,0]]}); 
      } 
    ); 
  </script>

<div class="pagination">
    <span class="step-links">
        {% if result_foias.has_previous %}
            <a href="?page={{ result_foias.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ result_foias.number }} of {{ result_foias.paginator.num_pages }}.
        </span>

        {% if result_foias.has_next %}
            <a href="?page={{ result_foias.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{%endblock%}

foias/templates/foias/detail.html
{% extends "base.html" %}

{% block content %}
<h1>FOIA for {{foia.agency}}</h1>

<p>By {{foia.reporter }}, filed {{foia.filed_date}}</p>

<p>This FOIA is <b>{{ foia.status }}</b></p>

<p>It was filed on <b>{{ foia.filed_date }}</b> and requested <b>{{ foia.request_subject }}</b></p>

<a href="{% url 'admin:foias_foia_change' foia.id %}">Edit</a>

{% endblock %}

foias/templates/foias/foiatable.html
<table class="alternaterows foiatable">
  <thead>
    <th>project</th>
    <th>filed</th>
    <th>with... </th>
    <th>for...</th>
    <th>status</th><!-- highlight if something's overdue? -->
    <th>next due date</th>
    <th>by... </th>          
    <th><!-- edit button goes here --></th>
  </thead>
  <tbody>
{% for foia in foias %}
    <!-- TODO: if it's your FOIA, link you to the admin page? -->
    <tr>
      <td>
      {% for tag in foia.tags.all %}
        <a href="{% url 'foias:project' tag.id %}">{{tag.name}}</a>
      {% endfor %}
      </td>
      <td>{{ foia.filed_date }}</td>
      <td>{{ foia.agency }}</td>
      <td>{{ foia.request_subject|truncatechars:50 }}</td>
      <td>{{ foia.status }}</td>
      <td>{{ foia.next_due_date }}</td>
      <td>{{ foia.reporter }}</td>
      <td><span style="display: none;">{{ foia.sort_order }} {{foia.sortable_filed_date}}</span> <a class="btn btn-default btn-block" href="{% url 'admin:foias_foia_change' foia.id %}">View / Edit</a></td>
    </tr>
{% endfor %}
  </tbody>
</table>

foias/templates/foias/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">

{% if warn_about_holidays  %}
  <div class="row" style="background-color: #fcc; padding: 5px;">
    <p>WARNING: This app only knows about federal holidays through 2020. It's almost 2021. If this app is still in use, please remind its maintainer to add more federal holiday dates (in models.py). (This means you, o reader! Only you can prevent forest fires.)</p>
  </div>
{% endif %}

  <div class="row" >
    <div class="col-md-12">
      <h4>Activity</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>{{ my_foias_count }}</h2>
      <p class="lead">FOIAs you've tracked here.</p>
    </div>
    <div class="col-md-3">
      <h2>{{ all_foias_count }}</h2>
      <p class="lead">total FOIAs tracked here.</p>
    </div>
    <div class="col-md-3">
      <h2>{{ percent_overdue }}%</h2>
      <p class="lead">of FOIAs are overdue.</p>
    </div>
    <div class="col-md-3">
      <h2>{{ percent_complete }}%</h2>
      <p class="lead">of FOIAs have been completed.</p>
    </div>
  </div>

  <div class="row" style="font-size: 16px; border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p>If you track your FOIAs here, you can benefit from: </p>
      <ul>
        <li>automatic <b>email reminders</b> of deadlines when a response or appeal is due</li>
        <li>easier collaboration, since you'll know who may have already filed a <b>similar requests</b></li>
        <li>coordination with <b>your PR people or lawyers</b> if pressure or litigation becomes necessary</li>
      </ul>
  </div>


  <div class="row" >
    <a class="btn btn-default btn-lg btn-block" href="{% url 'admin:foias_foia_add' %}">
      Track Your FOIA
    </a>
  </div>


  {% if my_foias %}
  <div class="row" style="border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of FOIAs you've filed: </p>
  </div>
    {% include "foias/foiatable.html" with foias=my_foias only %}
  {% else %}
      <p>Looks like you haven't recorded any of your FOIAs here. <a href="{% url 'admin:foias_foia_add' %}">Give it a try!</a> It's quick and easy.</p>
  {% endif %}


  {% if project_foias %}
  <div class="row" style="border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of FOIAs in the project named <strong>{{ project_name }}</strong>: </p>
  </div>
    {% include "foias/foiatable.html" with foias=project_foias only %}
  {% endif %}



  <div class="row" style="margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of FOIAs filed recently by your colleagues: </p>

    {% if latest_foias %}
      <form action="{% url 'foias:search' %}" ><p>See <a href="{% url 'foias:all' %}">all FOIA filed by everyone</a> or search: <input style="border: 1px solid #ccc; border-radius: 4px; padding: 5px 6px; margin-top: 0;" type="text" name="q" placeholder="Trump planes" /> <button class="btn btn-default" type="submit">Search</button></p></form>
      {% include "foias/foiatable.html" with foias=latest_foias only %}

    {% else %}
        <p>No one else has filed a FOIA!</p>
    {% endif %}
  </div>

  {% endblock %}
</div>
{% block extrajs %}
  <script type="text/javascript">
    $(document).ready(function() 
      { 
        $('.foiatable').each(function(i, el){
          $(el).tablesorter({"sortList": [[6,0]]}); 
        })
      } 
    ); 
  </script>

{%endblock%}

foias/templates/foias/project.html
{% extends "base.html" %}

{% block content %}
  <div class="container">

  {% if project_foias %}
  <div class="row" style="border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of FOIAs tagged <strong>{{ project_name }}</strong>: </p>
  </div>

    {% include "foias/foiatable.html" with foias=project_foias only %}
  {% else %}
      <p>Sorry, there are no FOIAs in the <strong>{{ project_name }}</strong> project.</b></p>
  {% endif %}


  {% endblock %}
</div>
{% block extrajs %}
  <script type="text/javascript">
    $(document).ready(function() 
      { 
        $("#foiastatus").tablesorter({"sortList": [[6,0]]}); 
      } 
    ); 
  </script>

{%endblock%}

foias/templates/foias/search.html
{% extends "base.html" %}

{% block content %}
  <div class="container">

  {% if result_foias %}
  <div class="row" style="border-top: 1em solid #336; margin-top: 20px; padding-top: 20px;">
    <p class="lead">Here's a list of results: </p>
  </div>

    {% include "foias/foiatable.html" with foias=result_foias only %}
  {% else %}
      <p>Sorry, there are no results matching your query for <b>{{ query }}</b></p>
  {% endif %}


  {% endblock %}
</div>
{% block extrajs %}
  <script type="text/javascript">
    $(document).ready(function() 
      { 
        $("#foiastatus").tablesorter({"sortList": [[6,0]]}); 
      } 
    ); 
  </script>

{%endblock%}